version: '3.9'


services:
  scraper:
    container_name: '${PROJECT_NAME}_scraper'
    restart: on-failure
    build:
      context: .
      dockerfile: .docker/scraper/Dockerfile
    env_file:
      - .env
